site_name: IT50

theme:
  language: zh
  name: material
  features:
    - navigaion.instant
    - navigation.tabs
    - navigation.indexes

nav:
  - 关于: zh-Hans/
  - 理论:
    - zh-Hans/theory/index.md
    - 数据:
      - zh-Hans/theory/data.md
      - 二进制数据: zh-Hans/theory/binary-data.md
      - 文字编码: zh-Hans/theory/text-encoding.md
      - 文件格式: zh-Hans/theory/file-format.md
      - 分区和文件系统: zh-Hans/theory/partitioning-and-filesystem.md
    - 程序:
      - zh-Hans/theory/program.md
    - 密码学:
      - zh-Hans/theory/cryptography.md
      - 密码学哈希: zh-Hans/theory/cryptographic-hash.md
      - 对称密码学: zh-Hans/theory/symmetric-cryptography.md
      - 非对称密码学: zh-Hans/theory/asymmetric-cryptography.md
      - 公钥基础设施: zh-Hans/theory/public-key-infrastructure.md
    - 网络:
      - none
  - 试验练习:
    - zh-Hans/lab/index.md
    - GNU/Linux:
      - zh-Hans/lab/gnu-linux/index.md
      - 密码学哈希: zh-Hans/lab/gnu-linux/cryptographic-hash.md
    - macOS: zh-Hans/lab/macos
    - Windows: zh-Hans/lab/windows

extra:
  homepage: zh-Hans/
  alternate:
    - name: English
      link: en/
      lang: en
    - name: 中文（简体）
      link: zh-Hans/
      lang: zh

markdown_extensions:
  - extra
  - meta
  - def_list
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.snippets
  - pymdownx.keys
